language: node_js
node_js:
  - "12.22.7"
services: 
  - postgresql
env:
   - DATABASE_URL=postgresql://postgres@localhost:5432/coderdb
before_script:
  - psql -c 'create database coderdb;' -U postgres
  - psql -U postgres -d coderdb -a -f registrations.sql